In [1]:
import client_server
import rng

### Create device

In [2]:
rng = rng.RNG()

In [3]:
rng.set_params(mean=1.5, amp=2.5)

In [4]:
rng.get_value((10, 10))

array([[0.64060743, 0.59210521, 1.42723884, 1.05094607, 1.6452166 ,
        1.70624326, 0.89223931, 1.57608019, 2.48928704, 1.14094624],
       [2.50563576, 1.1860154 , 2.04940509, 0.61958214, 1.96579673,
        2.49875306, 0.44119886, 1.70802859, 2.15019149, 1.67679021],
       [0.5143915 , 1.90617532, 2.00260158, 0.88774977, 1.28285576,
        1.51485299, 2.23135913, 1.64560339, 1.01441522, 1.80810714],
       [1.21021797, 2.5711968 , 2.70545927, 2.36258735, 1.98415756,
        1.9898958 , 0.81538222, 1.73334619, 0.94032744, 0.59516962],
       [0.41163948, 2.70261648, 1.27010032, 0.68602935, 0.32771197,
        2.16584582, 0.36069863, 2.59554484, 1.19161636, 2.7362467 ],
       [1.79711729, 1.14567633, 2.6847532 , 1.72466816, 2.14702266,
        2.45050837, 1.22634715, 0.48082421, 0.9665956 , 0.62688146],
       [1.16312283, 0.25494664, 1.34153659, 0.655742  , 1.88815376,
        2.62860134, 0.38121558, 1.94636016, 0.83577556, 1.45249542],
       [2.61429385, 2.55717812, 1.2473618

In [5]:
rng.generate_test_array(100)

In [6]:
rng.test_array

array([0.86590294, 0.87342418, 0.44266281, 0.49423842, 0.10949357,
       0.26131254, 0.27294448, 0.44398981, 0.2404992 , 0.86624868,
       0.67101216, 0.60242112, 0.52494017, 0.14601541, 0.54663305,
       0.4702951 , 0.53630367, 0.70326435, 0.17076992, 0.70037057,
       0.65663665, 0.49456751, 0.13383383, 0.25535824, 0.15434457,
       0.88366267, 0.35221875, 0.27568457, 0.79947459, 0.99993691,
       0.91615475, 0.65733399, 0.84837039, 0.01597871, 0.21403851,
       0.471125  , 0.43022724, 0.83566195, 0.62670826, 0.16558576,
       0.2165692 , 0.50028478, 0.57450906, 0.87034156, 0.5708791 ,
       0.71310119, 0.19804897, 0.37065674, 0.04483494, 0.86430911,
       0.99921628, 0.00197881, 0.95484465, 0.17065647, 0.56702252,
       0.4383046 , 0.30498855, 0.0091488 , 0.98756631, 0.90430098,
       0.14979589, 0.63225737, 0.62906474, 0.96993289, 0.51082962,
       0.08057571, 0.08207526, 0.44464277, 0.75048121, 0.77837099,
       0.07695029, 0.9283835 , 0.76107198, 0.52703921, 0.72647

In [7]:
rng.get_test_array_tuple()

(0.8659029430333672,
 0.8734241784071445,
 0.44266281048029654,
 0.4942384211744303,
 0.10949357045577057,
 0.2613125446457568,
 0.272944478853421,
 0.4439898113736185,
 0.24049919635349593,
 0.8662486759941614,
 0.6710121631734648,
 0.6024211201609742,
 0.5249401661418815,
 0.14601541271475216,
 0.5466330467483722,
 0.47029510425644805,
 0.5363036682354493,
 0.7032643528808326,
 0.17076992192321616,
 0.7003705651869774,
 0.6566366470972607,
 0.4945675133546318,
 0.13383382963512647,
 0.25535823671283187,
 0.15434457090623688,
 0.8836626691225723,
 0.35221874975743905,
 0.27568456628746263,
 0.7994745947039016,
 0.9999369137262574,
 0.9161547501051168,
 0.6573339872624868,
 0.8483703860403807,
 0.015978710253850892,
 0.21403850751310594,
 0.47112499558295273,
 0.43022723648198047,
 0.8356619464654614,
 0.6267082557070275,
 0.16558575914247697,
 0.21656919785527828,
 0.5002847838259576,
 0.5745090622351808,
 0.8703415555353644,
 0.570879096161562,
 0.7131011857588001,
 0.198048968341176

In [8]:
rng.get_test_array_tostring()

b'\xb1\xd4\xba\x16z\xb5\xeb?[k9C\x17\xf3\xeb?\xc0\xc5\x8ae\x96T\xdc?\n\xbc\xd7/\x9a\xa1\xdf?\x98\xd4:H\xc5\x07\xbc?\xaaoR@X\xb9\xd0?4&\x93\x1e\xecw\xd1?t\xd7\xe6=Tj\xdc?\xe0\xb9\x86{\xad\xc8\xce?\xa6$\xb3$O\xb8\xeb?=\x8b\x01\x80\xeex\xe5?\xb0Z0\xa8\x08G\xe3?@\xf5\xbdQO\xcc\xe0?\xd80)\x0f\xa2\xb0\xc2?\xa0NV\x96\x04~\xe1?\xd0\x05\x10\xa3P\x19\xde?\x8fyyOf)\xe1?\xdd\x1a\x82>$\x81\xe6?\xe8|\xe6\xee\xc9\xdb\xc5?.\xe4\x11\x88oi\xe6?\x16i\x94\xdb*\x03\xe5?\x82k\xe1\x7f\xfe\xa6\xdf?\x90\xce\xb0\x88w!\xc1?\xa2\x88\xdc\x12\xcaW\xd0?\x9c\xc0-\x1a\x90\xc1\xc3?\x05{\x12\xef\xf6F\xec?\xe2\xc1\xcf\x82\xc0\x8a\xd6?\xb6\xdc\r\xe1\xd0\xa4\xd1?;\x8e\xc7\xbeK\x95\xe9?\xf1\x8e\xd0\xb2{\xff\xef?T\xd98\xc4#Q\xed?\xe4\xee:I\xe1\x08\xe5?\xcd\x06\xde\xa6\xd9%\xeb?\x00\xe4\xe3\x17\xb9\\\x90?\x88=\xed"\x9de\xcb?\xe2\xd7\x16t\xe9&\xde?\xd6w\xa2\xd1\xd7\x88\xdb?g\x96R\x1f\xbe\xbd\xea?\xed\xa2\xccx\xfe\r\xe4?\x80\xa2\x19\x06\xea1\xc5?\xf4\xff\r\x1b\x8a\xb8\xcb?`\x01\'<U\x02\xe0?\x8b\xc81\xd4`b\xe2?\x1a\xf9\xab\x88\x

In [9]:
rng.get_test_array_pickle()

b'\x80\x03cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02C\x01bq\x03\x87q\x04Rq\x05(K\x01Kd\x85q\x06cnumpy\ndtype\nq\x07X\x02\x00\x00\x00f8q\x08K\x00K\x01\x87q\tRq\n(K\x03X\x01\x00\x00\x00<q\x0bNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x0cb\x89B \x03\x00\x00\xb1\xd4\xba\x16z\xb5\xeb?[k9C\x17\xf3\xeb?\xc0\xc5\x8ae\x96T\xdc?\n\xbc\xd7/\x9a\xa1\xdf?\x98\xd4:H\xc5\x07\xbc?\xaaoR@X\xb9\xd0?4&\x93\x1e\xecw\xd1?t\xd7\xe6=Tj\xdc?\xe0\xb9\x86{\xad\xc8\xce?\xa6$\xb3$O\xb8\xeb?=\x8b\x01\x80\xeex\xe5?\xb0Z0\xa8\x08G\xe3?@\xf5\xbdQO\xcc\xe0?\xd80)\x0f\xa2\xb0\xc2?\xa0NV\x96\x04~\xe1?\xd0\x05\x10\xa3P\x19\xde?\x8fyyOf)\xe1?\xdd\x1a\x82>$\x81\xe6?\xe8|\xe6\xee\xc9\xdb\xc5?.\xe4\x11\x88oi\xe6?\x16i\x94\xdb*\x03\xe5?\x82k\xe1\x7f\xfe\xa6\xdf?\x90\xce\xb0\x88w!\xc1?\xa2\x88\xdc\x12\xcaW\xd0?\x9c\xc0-\x1a\x90\xc1\xc3?\x05{\x12\xef\xf6F\xec?\xe2\xc1\xcf\x82\xc0\x8a\xd6?\xb6\xdc\r\xe1\xd0\xa4\xd1?;\x8e\xc7\xbeK\x95\xe9?\xf1\x8e\xd0\xb2{\xff\xef?T\xd98\xc4#Q\xed?\xe4\xee:I

### Create and start server 

In [10]:
rng_server = client_server.Server(
    module_ref=rng, 
    host='localhost', 
    port=18890
)

In [11]:
rng_server.start()

In [12]:
rng_server

In [22]:
rng.test_array.shape

(100000,)

C:\Anaconda\lib\site-packages\rpyc\core\protocol.py:590: RuntimeWarning: divide by zero encountered in true_divide
  return obj(*args, **dict(kwargs))


In [16]:
len(rng.test_array)

1000

In [11]:
rng._mean = 3.5

In [12]:
rng._amp = 4.5

In [26]:
rng.get_params()

{'mean': 1.5, 'amp': 2.5}

In [19]:
rng.get_value(10)

array([1.93198863, 5.35982638, 1.83790444, 4.57233581, 2.1681187 ,
       1.84905056, 4.42055605, 3.89569589, 4.1030336 , 3.12608331])